name: Docker Image Build + Scan + Publish
on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/docker-image.yaml"
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: ci-${{ github.repository }}-docker-pipeline

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ecr_repo_name: ${{ steps.set-repo.outputs.ecr_repo_name }}
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4
      - name: Prepare ECR repo name
        id: set-repo
        run: |
          set -eux
          # lowercase the name
          repo="${GITHUB_REPOSITORY,,}"
          # replace / with _
          echo "ECR_REPO_NAME=${repo//\//_}" >> $GITHUB_ENV

      - name: Set image tag
        id: set-tag
        run: |
          set -eux
          tag="${{ vars.image_tag }}-${GITHUB_SHA::7}"
          echo "image_tag=$tag" >> "$GITHUB_OUTPUT"
          
  provision-ecr:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ vars.role_to_assume_tf_state }}
          aws-region: ${{ vars.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: TF init
        run: |
          terraform init -upgrade -reconfigure \
            -backend-config='region=${{ vars.aws_region }}' \
            -backend-config='bucket=${{ vars.backend_s3_bucket }}' \
            -backend-config='key=${{ vars.ecr_key }}' \
            -backend-config='use_lockfile=true'
        working-directory: bootstrap/ecr_bootstrap

      - name: TF apply - Create ECR repo
        run: |
          terraform apply \
            -var 'repository_name=${{ needs.prepare.outputs.ecr_repo_name }}' \
            -var 'lifecycle_policy=${{ vars.lifecycle_policy_file }}' \
            -var 'iam_role=arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.githubb_iam_role }}' \
            -var 'aws_account_id=${{ vars.aws_account_id }}' \
            -auto-approve
        working-directory: bootstrap/ecr_bootstrap

  build-and-scan:
    runs-on: ubuntu-latest
    needs: provision-ecr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t ${{ vars.image_tag }}:${{ needs.prepare.outputs.image_tag }} .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ vars.image_tag }}:${{ needs.prepare.outputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  push-image:
    runs-on: ubuntu-latest
    needs: build-and-scan
    permissions:
      id-token: write
      contents: read

    outputs:
      full_image: ${{ steps.push.outputs.full_image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ vars.role_to_assume_tf_state }}
          aws-region: ${{ vars.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ vars.aws_account_id }}

      - name: Build, tag and push to ECR
        id: push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.prepare.outputs.ecr_repo_name }}
          IMAGE_TAG: ${{ needs.prepare.outputs.image_tag }}
        run: |
          docker build -f "${{ vars.path_to_dockerfile }}" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

  deploy-ecs:
    runs-on: ubuntu-latest
    needs: push-image
    permissions:
      id-token: write
      contents: read

    environment: prod

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ vars.role_to_assume_tf_state }}
          aws-region: ${{ vars.aws_region }}

      - name: Get latest task definition ARN
        id: get-task-def
        run: |
          ARN=$(aws ecs describe-task-definition \
            --task-definition ecs_task_definition \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "task_definition_arn=$ARN" >> "$GITHUB_OUTPUT"

      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn: ${{ steps.get-task-def.outputs.task_definition_arn }}
          container-name: threat-app
          image: ${{ needs.push-image.outputs.full_image }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.6.0
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ecs_proj_service
          cluster: ecs_cluster
          wait-for-service-stability: true
